server:
  port: 8010
  shutdown: graceful

spring:
  application:
    name: standalone
  lifecycle:
    timeout-per-shutdown-phase: 20s
  kafka:
    bootstrap-servers: 172.23.104.50:9092,172.23.104.50:9093,172.23.104.50:9094
    producer:
      retries: 1
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

management:
  health:
    probes:
      enabled: true
